use crate::time::{SimulationClock, SimulationTime};
use bevy::ecs::system::{Command, Deferred, SystemBuffer, SystemMeta, SystemParam};
use bevy::prelude::*;
use std::fmt::Debug;
use std::marker::PhantomData;

/// An instantaneous change on the world state, the [`bevy::prelude::World`] during a simulation.
pub trait Prediction: Command + Clone + Send + Sync + Debug + 'static {
    fn name() -> &'static str {
        let full_name = std::any::type_name::<Self>();
        let prefix_end = full_name.find('<').unwrap_or(full_name.len());

        match full_name[..prefix_end].rfind("::") {
            Some(index) => &full_name[index + 2..],
            None => full_name,
        }
    }
}

impl<T> Prediction for T where T: Command + Clone + Send + Sync + Debug + 'static {}

mod sealed {
    pub trait Sealed {}
}

// TODO(@reuben-thomas): Follow doc format specified in https://rust-lang.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed
impl<T> sealed::Sealed for T where T: Prediction {}

pub trait DynPrediction: sealed::Sealed + Debug + Send + Sync + 'static {
    fn apply(self: Box<Self>, world: &mut World);

    fn clone_to_box(&self) -> Box<dyn DynPrediction>;

    fn name(&self) -> &'static str;
}

impl<T: Prediction> DynPrediction for T {
    fn apply(self: Box<Self>, world: &mut World) {
        Command::apply(*self, world)
    }

    fn clone_to_box(&self) -> Box<dyn DynPrediction> {
        Box::new(self.clone())
    }

    fn name(&self) -> &'static str {
        <T as Prediction>::name()
    }
}

impl Clone for Box<dyn DynPrediction> {
    fn clone(&self) -> Self {
        self.clone_to_box()
    }
}

/// A resource for holding predictions generated by prediciton systems.
///
/// A prediction is selected by the following criteria, ranked by priority:
/// 1. [`Prediction`]` custom ordering @TODO(@reuben-thomas)
/// 2. Earliest to be submitted (determined by system execution ordering).
/// 3. Event name TODO(@reuben-thomas)
///
#[derive(Resource, Default)]
pub struct Predictions(Option<(SimulationTime, Vec<Box<dyn DynPrediction>>)>);

impl Predictions {
    /// The time of the next series of predictions, if any.
    pub fn next_time(&self) -> Option<SimulationTime> {
        self.0.as_ref().map(|(next_time, _)| *next_time)
    }

    /// Submit a discrete event that might occur at a time in the future.
    ///
    /// The event is discarded if it is earlier than the current time.
    fn submit(
        &mut self,
        now: SimulationTime,
        event_time: SimulationTime,
        event: Box<dyn DynPrediction>,
    ) {
        if event_time < now {
            warn!(
                "Discarding event {} scheduled at time {event_time:?}, \
                which is earlier than the current time {now:?} \
                and will never be executed.",
                event.name(),
            );
            return;
        }
        match &mut self.0 {
            Some((time, events)) if event_time == *time => events.push(event),
            Some((time, _)) if event_time > *time => {}
            _ => self.0 = Some((event_time, vec![event])),
        }
    }

    /// Removes and returns the highest priority prediction, if any.
    ///
    /// The event may be scheduled for any time at or after the time it was
    /// submitted, use [`Self::next_time`] to check when it is due.
    pub fn pop_highest_priority(&mut self) -> Option<Box<dyn DynPrediction>> {
        let (_, events) = self.0.as_mut()?;
        let event = events.remove(0);
        if events.is_empty() {
            self.0 = None;
        }
        Some(event)
    }

    /// Discards all events.
    pub fn discard_all(&mut self) {
        self.0 = None;
    }
}

impl SystemBuffer for Predictions {
    fn apply(&mut self, _system_meta: &SystemMeta, world: &mut World) {
        let Some((time, buffered)) = self.0.take() else {
            return;
        };
        let mut events = world.resource_mut::<Predictions>();
        for event in buffered {
            events.submit(time, time, event);
        }
    }
}

/// Keeps track of predictions.
#[derive(SystemParam)]
pub struct PredictionWriter<'w, 's> {
    buffer: Deferred<'s, Predictions>,
    clock: Res<'w, SimulationClock>,
}

impl PredictionWriter<'_, '_> {
    /// Predict that a custom event type will occur in the future.
    pub fn predict(&mut self, time: SimulationTime, event: impl Prediction) {
        self.buffer.submit(self.clock.now(), time, Box::new(event));
    }

    /// Predict that an instantaneous event will take place. An instantaneous
    /// event does not advance the simulation clock. This is most often used
    /// when a custom prediction system is being used to extend or modify the
    /// behavior of a base (upstream) prediction system.
    pub fn predict_instantaneous(&mut self, event: impl Prediction) {
        self.predict(self.clock.now(), event);
    }

    /// Predict an insertion of components into an entity. Pass in a component
    /// or bundle to insert into an entity if this prediction is selected.
    ///
    /// Inserted component values will replace any component values of the same
    /// type that the entity already had.
    pub fn predict_insert<T: Bundle + Clone + Debug>(
        &mut self,
        time: SimulationTime,
        entity: Entity,
        value: T,
    ) {
        self.buffer.submit(
            self.clock.now(),
            time,
            Box::new(BundlePrediction { entity, value }),
        );
    }

    /// Predict an instantaneous insertion of components into an entity.
    pub fn predict_instantaneous_insert<T: Bundle + Clone + Debug>(
        &mut self,
        entity: Entity,
        value: T,
    ) {
        self.predict_insert(self.clock.now(), entity, value);
    }

    /// Predict a resource being inserted into the world.
    ///
    /// Inserted resource values will replace any resource of the same type that
    /// the world already had.
    pub fn predict_resource_insert<R: Resource + Clone + Debug>(
        &mut self,
        time: SimulationTime,
        value: R,
    ) {
        self.buffer.submit(
            self.clock.now(),
            time,
            Box::new(ResourcePrediction { value }),
        );
    }

    /// Predict an instantaneous insertion of a resource into the world.
    pub fn predict_instantaneous_resource_insert<R: Resource + Clone + Debug>(&mut self, value: R) {
        self.predict_resource_insert(self.clock.now(), value);
    }
}

#[derive(Clone, Debug)]
struct BundlePrediction<T: Bundle + Clone + Debug> {
    entity: Entity,
    value: T,
}

impl<T: Bundle + Clone + Debug> Command for BundlePrediction<T> {
    fn apply(self, world: &mut World) {
        world.entity_mut(self.entity).insert(self.value);
    }
}

#[derive(Clone, Debug)]
struct ResourcePrediction<R: Resource + Clone + Debug> {
    value: R,
}

// TODO(@reuben-thomas): Fail if the resource already exists?
impl<R: Resource + Clone + Debug> Command for ResourcePrediction<R> {
    fn apply(self, world: &mut World) {
        world.insert_resource(self.value);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    /// An event that records its id to [`AppliedEvents`] when executed.
    #[derive(Clone, Debug)]
    struct RecordPrediction(u32);

    impl Command for RecordPrediction {
        fn apply(self, world: &mut World) {
            world.resource_mut::<AppliedEvents>().0.push(self.0);
        }
    }

    /// The ids of the [`RecordPrediction`]s applied to a world, in execution order.
    #[derive(Resource, Default)]
    struct AppliedEvents(Vec<u32>);

    fn create_test_world() -> World {
        let mut world = World::new();
        world.init_resource::<Predictions>();
        world.init_resource::<SimulationClock>();
        world.init_resource::<AppliedEvents>();
        world
    }

    /// Submits a [`RecordPrediction`] with the given id as a prediction for `event_time`.
    fn submit(world: &mut World, now: SimulationTime, event_time: SimulationTime, id: u32) {
        world
            .resource_mut::<Predictions>()
            .submit(now, event_time, Box::new(RecordPrediction(id)));
    }

    /// Pops and applies every prediction at `now`, returning popped ids.
    fn pop_and_apply_all(world: &mut World, now: SimulationTime) -> Vec<u32> {
        while next_time(world) == Some(now) {
            let Some(event) = world.resource_mut::<Predictions>().pop_highest_priority() else {
                break;
            };
            event.apply(world);
        }
        world.resource::<AppliedEvents>().0.clone()
    }

    /// Get the current next time among predictions.
    fn next_time(world: &mut World) -> Option<SimulationTime> {
        world.resource::<Predictions>().next_time()
    }

    #[test]
    fn test_only_earliest_predictions_retained() {
        let mut world = create_test_world();
        submit(&mut world, create_time(0), create_time(2), 2);
        submit(&mut world, create_time(0), create_time(1), 1);
        submit(&mut world, create_time(0), create_time(3), 3);
        submit(&mut world, create_time(0), create_time(1), 4);

        assert_eq!(
            next_time(&mut world),
            Some(create_time(1)),
            "Only events from the earliest time should remain."
        );
        assert_eq!(
            pop_and_apply_all(&mut world, create_time(1)),
            vec![1, 4],
            "All predictions at the earliest time should be executed in order of submission"
        );
        assert_eq!(next_time(&mut world), None,);
    }

    #[test]
    fn test_predictions_before_now_discarded() {
        let mut world = create_test_world();
        submit(&mut world, create_time(2), create_time(1), 1);

        assert_eq!(
            next_time(&mut world),
            None,
            "An event that can never be executed should not be held as a prediction."
        );
    }

    fn create_time(seconds: u64) -> SimulationTime {
        SimulationTime::new(Duration::from_secs(seconds))
    }
}
