use crate::time::{SimulationClock, SimulationTime};
use bevy::ecs::system::{Command, Deferred, SystemBuffer, SystemMeta, SystemParam};
use bevy::prelude::*;
use std::fmt::Debug;
use std::marker::PhantomData;

/// An instantaneous change on the world state, the [`bevy::prelude::World`] during a simulation.
pub trait DiscreteEvent: Command + Clone + Send + Sync + Debug + 'static {
    fn name() -> &'static str {
        let full_name = std::any::type_name::<Self>();
        let prefix_end = full_name.find('<').unwrap_or(full_name.len());

        match full_name[..prefix_end].rfind("::") {
            Some(index) => &full_name[index + 2..],
            None => full_name,
        }
    }
}

impl<T> DiscreteEvent for T where T: Command + Clone + Send + Sync + Debug + 'static {}

mod sealed {
    pub trait Sealed {}
}

// TODO(@reuben-thomas): Follow doc format specified in https://rust-lang.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed
impl<T> sealed::Sealed for T where T: DiscreteEvent {}

pub trait DynDiscreteEvent: sealed::Sealed + Debug + Send + Sync + 'static {
    fn apply(self: Box<Self>, world: &mut World);

    fn clone_to_box(&self) -> Box<dyn DynDiscreteEvent>;

    fn name(&self) -> &'static str;
}

impl<T: DiscreteEvent> DynDiscreteEvent for T {
    fn apply(self: Box<Self>, world: &mut World) {
        Command::apply(*self, world)
    }

    fn clone_to_box(&self) -> Box<dyn DynDiscreteEvent> {
        Box::new(self.clone())
    }

    fn name(&self) -> &'static str {
        <T as DiscreteEvent>::name()
    }
}

impl Clone for Box<dyn DynDiscreteEvent> {
    fn clone(&self) -> Self {
        self.clone_to_box()
    }
}

/// A resource for holding candidate events generated by prediciton systems.
///
/// A candidate event is selected by the following criteria, ranked by priority:
/// 1. [`DiscreteEvent`]` custom ordering @TODO(@reuben-thomas)
/// 2. Earliest to be submitted (determined by system execution ordering).
/// 3. Event name TODO(@reuben-thomas)
///
#[derive(Resource, Default)]
pub struct CandidateDiscreteEvents(Option<(SimulationTime, Vec<Box<dyn DynDiscreteEvent>>)>);

impl CandidateDiscreteEvents {
    /// The time of the next series of candidate events, if any.
    pub fn next_time(&self) -> Option<SimulationTime> {
        self.0.as_ref().map(|(next_time, _)| *next_time)
    }

    /// Submit a discrete event that might occur at a time in the future.
    ///
    /// The event is discarded if it is earlier than the current time.
    fn submit(
        &mut self,
        now: SimulationTime,
        event_time: SimulationTime,
        event: Box<dyn DynDiscreteEvent>,
    ) {
        if event_time < now {
            warn!(
                "Discarding event {} scheduled at time {event_time:?}, \
                which is earlier than the current time {now:?} \
                and will never be executed.",
                event.name(),
            );
            return;
        }
        match &mut self.0 {
            Some((time, events)) if event_time == *time => events.push(event),
            Some((time, _)) if event_time > *time => {}
            _ => self.0 = Some((event_time, vec![event])),
        }
    }

    /// Removes and returns the highest priority candidate event, if any.
    ///
    /// The event may be scheduled for any time at or after the time it was
    /// submitted, use [`Self::next_time`] to check when it is due.
    pub fn pop_highest_priority_event(&mut self) -> Option<Box<dyn DynDiscreteEvent>> {
        let (_, events) = self.0.as_mut()?;
        let event = events.remove(0);
        if events.is_empty() {
            self.0 = None;
        }
        Some(event)
    }

    /// Discards all events.
    pub fn discard_all(&mut self) {
        self.0 = None;
    }
}

impl SystemBuffer for CandidateDiscreteEvents {
    fn apply(&mut self, _system_meta: &SystemMeta, world: &mut World) {
        let Some((time, buffered)) = self.0.take() else {
            return;
        };
        let mut events = world.resource_mut::<CandidateDiscreteEvents>();
        for event in buffered {
            events.submit(time, time, event);
        }
    }
}

/// Predicts [`DiscreteEvent`]s that may occur.
///
/// In most cases, you should use [`CandidateComponentEventWriter`] or
/// [`CandidateResourceEventWriter`] if you do not wish to implement a
/// [`DiscreteEvent`] struct.
#[derive(SystemParam)]
pub struct CandidateEventWriter<'w, 's> {
    buffer: Deferred<'s, CandidateDiscreteEvents>,
    clock: Res<'w, SimulationClock>,
}

impl CandidateEventWriter<'_, '_> {
    pub fn predict(&mut self, time: SimulationTime, event: impl DiscreteEvent) {
        self.buffer.submit(self.clock.now(), time, Box::new(event));
    }

    pub fn predict_now(&mut self, event: impl DiscreteEvent) {
        self.predict(self.clock.now(), event);
    }
}

/// Predicts a component write as a discrete event.
#[derive(SystemParam)]
pub struct CandidateComponentEventWriter<'w, 's, T: Component + Clone + Debug> {
    buffer: Deferred<'s, CandidateDiscreteEvents>,
    clock: Res<'w, SimulationClock>,
    _marker: PhantomData<T>,
}

impl<T: Component + Clone + Debug> CandidateComponentEventWriter<'_, '_, T> {
    pub fn predict(&mut self, time: SimulationTime, entity: Entity, value: T) {
        self.buffer.submit(
            self.clock.now(),
            time,
            Box::new(CandidateComponentWrite { entity, value }),
        );
    }

    pub fn predict_now(&mut self, entity: Entity, value: T) {
        self.predict(self.clock.now(), entity, value);
    }
}

#[derive(Clone, Debug)]
struct CandidateComponentWrite<T: Component + Clone + Debug> {
    entity: Entity,
    value: T,
}

impl<T: Component + Clone + Debug> Command for CandidateComponentWrite<T> {
    fn apply(self, world: &mut World) {
        world.entity_mut(self.entity).insert(self.value);
    }
}

/// Predicts a resource write as a discrete event.
#[derive(SystemParam)]
pub struct CandidateResourceEventWriter<'w, 's, R: Resource + Clone + Debug> {
    buffer: Deferred<'s, CandidateDiscreteEvents>,
    clock: Res<'w, SimulationClock>,
    _marker: PhantomData<R>,
}

impl<R: Resource + Clone + Debug> CandidateResourceEventWriter<'_, '_, R> {
    pub fn predict(&mut self, time: SimulationTime, value: R) {
        self.buffer.submit(
            self.clock.now(),
            time,
            Box::new(CandidateResourceWrite { value }),
        );
    }

    pub fn predict_now(&mut self, value: R) {
        self.predict(self.clock.now(), value);
    }
}

#[derive(Clone, Debug)]
struct CandidateResourceWrite<R: Resource + Clone + Debug> {
    value: R,
}

// TODO(@reuben-thomas): Fail if the resource already exists?
impl<R: Resource + Clone + Debug> Command for CandidateResourceWrite<R> {
    fn apply(self, world: &mut World) {
        world.insert_resource(self.value);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    /// An event that records its id to [`AppliedEvents`] when executed.
    #[derive(Clone, Debug)]
    struct RecordEvent(u32);

    impl Command for RecordEvent {
        fn apply(self, world: &mut World) {
            world.resource_mut::<AppliedEvents>().0.push(self.0);
        }
    }

    /// The ids of the [`RecordEvent`]s applied to a world, in execution order.
    #[derive(Resource, Default)]
    struct AppliedEvents(Vec<u32>);

    fn create_test_world() -> World {
        let mut world = World::new();
        world.init_resource::<CandidateDiscreteEvents>();
        world.init_resource::<SimulationClock>();
        world.init_resource::<AppliedEvents>();
        world
    }

    /// Submits a [`RecordEvent`] with the given id as a candidate for `event_time`.
    fn submit(world: &mut World, now: SimulationTime, event_time: SimulationTime, id: u32) {
        world.resource_mut::<CandidateDiscreteEvents>().submit(
            now,
            event_time,
            Box::new(RecordEvent(id)),
        );
    }

    /// Pops and applies every candidate event at `now`, returning popped ids.
    fn pop_and_apply_all(world: &mut World, now: SimulationTime) -> Vec<u32> {
        while next_time(world) == Some(now) {
            let Some(event) = world
                .resource_mut::<CandidateDiscreteEvents>()
                .pop_highest_priority_event()
            else {
                break;
            };
            event.apply(world);
        }
        world.resource::<AppliedEvents>().0.clone()
    }

    /// Get the current next time among candidate events.
    fn next_time(world: &mut World) -> Option<SimulationTime> {
        world.resource::<CandidateDiscreteEvents>().next_time()
    }

    #[test]
    fn test_only_earliest_candidate_events_retained() {
        let mut world = create_test_world();
        submit(&mut world, create_time(0), create_time(2), 2);
        submit(&mut world, create_time(0), create_time(1), 1);
        submit(&mut world, create_time(0), create_time(3), 3);
        submit(&mut world, create_time(0), create_time(1), 4);

        assert_eq!(
            next_time(&mut world),
            Some(create_time(1)),
            "Only events from the earliest time should remain."
        );
        assert_eq!(
            pop_and_apply_all(&mut world, create_time(1)),
            vec![1, 4],
            "All candidates at the earliest time should be executed in order of submission"
        );
        assert_eq!(next_time(&mut world), None,);
    }

    #[test]
    fn test_candidate_events_before_now_discarded() {
        let mut world = create_test_world();
        submit(&mut world, create_time(2), create_time(1), 1);

        assert_eq!(
            next_time(&mut world),
            None,
            "An event that can never be executed should not be held as a candidate."
        );
    }

    fn create_time(seconds: u64) -> SimulationTime {
        SimulationTime::new(Duration::from_secs(seconds))
    }
}
