name: ci_windows
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

      # Run build
    - name: Install Rustup using win.rustup.rs
      run: |
        # Disable the download progress bar which can cause perf issues
        $ProgressPreference = "SilentlyContinue"
        Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe
        .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --default-toolchain=none
        del rustup-init.exe
        rustup target add x86_64-pc-windows-msvc
      shell: powershell

    - name: Test rmf_site_format
      run: |
        cd crates/rmf_site_format
        cargo test

    - name: Test rmf_site_editor
      run: |
        rustc -Vv
        cargo -V
        cargo test
      shell: cmd

